# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h-fC2aXp0SJLpkpiXlFcNUIcyKxXy43O
"""

"""
Exploratory Data Analysis (EDA)
Dataset: student-mat.csv

This script covers:
- Loading the dataset
- Basic overview
- Summary statistics
- Univariate and bivariate plots
- Correlation heatmap
- Outlier checks
- Simple insights based on correlations

"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import logging

sns.set(style="whitegrid")

# Configure logging for cleaner tracking
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s — %(levelname)s — %(message)s"
)

# Load the dataset

def load_dataset(path, sep=";"):
    try:
        df = pd.read_csv(path, sep=sep)
        logging.info(f"Loaded dataset. Shape: {df.shape}")
        return df
    except Exception as e:
        logging.error(f"Could not load dataset: {e}")
        return None


df = load_dataset("student-mat.csv")
if df is None:
    raise SystemExit("Dataset could not be loaded.")

numeric_cols = df.select_dtypes(include=np.number).columns


# Basic dataset overview

def dataset_overview(df):
    print("\n--- First 5 Rows ---")
    display(df.head())

    print("\n--- Dataset Info ---")
    print(df.info())

    print("\n--- Missing Values ---")
    print(df.isnull().sum())


dataset_overview(df)



# Summary statistics

def summary_statistics(df):
    print("\n--- Summary Statistics ---")
    display(df.describe().T)

    print("\n--- Numeric Column Insights ---")
    for col in numeric_cols:
        print(
            f"{col}: "
            f"Mean={df[col].mean():.2f}, "
            f"Median={df[col].median():.2f}, "
            f"Std={df[col].std():.2f}, "
            f"Skew={df[col].skew():.2f}, "
            f"Kurt={df[col].kurtosis():.2f}"
        )


summary_statistics(df)



# Univariate analysis

def plot_histograms(df):
    df[numeric_cols].hist(figsize=(16, 12), bins=20)
    plt.suptitle("Histogram of Numeric Columns", fontsize=16)
    plt.tight_layout()
    plt.show()


def plot_boxplots(df):
    plt.figure(figsize=(16, 7))
    sns.boxplot(data=df[numeric_cols], orient="h")
    plt.title("Boxplots (Outlier Check)")
    plt.show()


plot_histograms(df)
plot_boxplots(df)


# Correlation heatmap

def correlation_analysis(df):
    plt.figure(figsize=(14, 10))
    sns.heatmap(df[numeric_cols].corr(), cmap="coolwarm")
    plt.title("Correlation Heatmap")
    plt.show()


correlation_analysis(df)


# Outlier & anomaly check

def detect_anomalies(df):
    print("\n--- Outlier & Skewness Check ---")

    for col in numeric_cols:
        skew = df[col].skew()
        if abs(skew) > 1:
            print(f"{col}: High skew → might need transformation")

        Q1, Q3 = df[col].quantile([0.25, 0.75])
        IQR = Q3 - Q1
        outliers = df[(df[col] < Q1 - 1.5 * IQR) | (df[col] > Q3 + 1.5 * IQR)]

        if len(outliers) > 0:
            print(f"{col}: {len(outliers)} potential outliers de")

